### ISSUE TITLE
Drawing App force close

### ISSUE THREAD

**Issue by power7714** [firebase/AndroidDrawing#8] opened 2015-06-04 02:36 UTC
I'm trying to run this demo along with the web app demo and it force closes. Here's the logcat from eclipse:

06-03 19:33:08.376: E/AndroidRuntime(25396): FATAL EXCEPTION: main
06-03 19:33:08.376: E/AndroidRuntime(25396): Process: com.firebase.drawing, PID: 25396
06-03 19:33:08.376: E/AndroidRuntime(25396): com.firebase.client.FirebaseException: Failed to bounce to type
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:183)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.firebase.drawing.DrawingView$1.onChildAdded(DrawingView.java:61)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.firebase.client.core.ChildEventRegistration.fireEvent(ChildEventRegistration.java:48)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.firebase.client.core.view.DataEvent.fire(DataEvent.java:45)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.firebase.client.core.view.EventRaiser$1.run(EventRaiser.java:38)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at android.os.Handler.handleCallback(Handler.java:733)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at android.os.Looper.loop(Looper.java:136)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at android.app.ActivityThread.main(ActivityThread.java:5158)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at dalvik.system.NativeStart.main(Native Method)
06-03 19:33:08.376: E/AndroidRuntime(25396): Caused by: com.shaded.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class com.firebase.drawing.Segment] from String value; no single-String constructor/factory method
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.shaded.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createFromStringFallbacks(StdValueInstantiator.java:428)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.shaded.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:299)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1056)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:136)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:123)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.shaded.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.shaded.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:181)
06-03 19:33:08.376: E/AndroidRuntime(25396): 	... 13 more

**Comment by puf** [comment] 2015-06-04 17:16
It looks like you're trying to open a board that has an invalid structure. We try to catch most invalid data in the doodleboard rules.json. I went through some of the boards in the app just now and don't get this problem (though I caught a few other potential problems that I'll be pushing an update for in a minute).

Can you help me reproduce the problem? Does this happen on a specific board? Did you make changes to the code?

**Comment by puf** [comment] 2015-06-26 16:43
Ping @power7714. I will close this issue, since there's nothing I can do at the moment. Feel free to re-open if you can provide steps that help reproducing it.

**Closed by puf** 2015-06-26 16:43 UTC
